steps:
  - label: ":construction_worker: Build and push migrations image"
    command: scripts/build-migrations-image.sh

  - label: ":construction_worker: Build and push main image"
    command: scripts/build-main-image.sh

  - wait

  - label: ":mag: Test"
    command: scripts/test.sh

  - wait

  - label: ":shipit: Generate docs"
    command: scripts/update-docs.sh
