ALTER TABLE country_metadata
  ALTER COLUMN francophone TEXT NOT NULL,
  ALTER COLUMN vxdel_segment TEXT NOT NULL,
  ALTER COLUMN pine_5 BOOLEAN NOT NULL,
  ALTER COLUMN dove94 BOOLEAN NOT NULL,
  ALTER COLUMN gavi68 BOOLEAN NOT NULL,
  ALTER COLUMN gavi72 BOOLEAN NOT NULL,
  ALTER COLUMN gavi77 BOOLEAN NOT NULL,
  ALTER COLUMN dove96 BOOLEAN NOT NULL,
  ALTER COLUMN gavi_region TEXT NOT NULL;
