ALTER TABLE country_metadata
  ALTER COLUMN francophone SET NOT NULL,
  ALTER COLUMN vxdel_segment SET NOT NULL,
  ALTER COLUMN pine_5 SET NOT NULL,
  ALTER COLUMN dove94 SET NOT NULL,
  ALTER COLUMN gavi68 SET NOT NULL,
  ALTER COLUMN gavi72 SET NOT NULL,
  ALTER COLUMN gavi77 SET NOT NULL,
  ALTER COLUMN dove96 SET NOT NULL,
  ALTER COLUMN gavi_region SET NOT NULL;
