INSERT INTO activity_type VALUES ('none', 'No vaccination');
INSERT INTO activity_type VALUES ('routine', 'Routine vaccination');
INSERT INTO activity_type VALUES ('campaign', 'Campaign vaccination');
INSERT INTO activity_type VALUES ('campaign-reactive', 'Reactive campaign vaccination');

INSERT INTO burden_outcome VALUES (1, 'cases', 'cases');
INSERT INTO burden_outcome VALUES (2, 'cases_acute', 'cases_acute');
INSERT INTO burden_outcome VALUES (3, 'cases_acute_symptomatic', 'cases_acute_symptomatic');
INSERT INTO burden_outcome VALUES (4, 'cases_chronic', 'cases_chronic');
INSERT INTO burden_outcome VALUES (5, 'dalys', 'dalys');
INSERT INTO burden_outcome VALUES (6, 'deaths', 'deaths');
INSERT INTO burden_outcome VALUES (7, 'deaths_acute', 'deaths_acute');
INSERT INTO burden_outcome VALUES (8, 'fvps', 'fvps');
INSERT INTO burden_outcome VALUES (9, 'infections', 'infections');
INSERT INTO burden_outcome VALUES (10, 'deaths_chronic', 'deaths_chronic');
INSERT INTO burden_outcome VALUES (11, 'cases_pneumo', 'cases_pneumo');
INSERT INTO burden_outcome VALUES (12, 'dalys_pneumo', 'dalys_pneumo');
INSERT INTO burden_outcome VALUES (13, 'deaths_pneumo', 'deaths_pneumo');
INSERT INTO burden_outcome VALUES (14, 'cases_men', 'cases_men');
INSERT INTO burden_outcome VALUES (15, 'dalys_men', 'dalys_men');
INSERT INTO burden_outcome VALUES (16, 'deaths_men', 'deaths_men');
INSERT INTO burden_outcome VALUES (17, 'deaths_averted', 'deaths_averted (LEGACY ONLY)');
INSERT INTO burden_outcome VALUES (18, 'da_rate', 'da_rate (LEGACY ONLY)');

INSERT INTO country VALUES ('AFG', 'Afghanistan');
INSERT INTO country VALUES ('ALA', 'Aland Islands');
INSERT INTO country VALUES ('ALB', 'Albania');
INSERT INTO country VALUES ('DZA', 'Algeria');
INSERT INTO country VALUES ('ASM', 'American Samoa');
INSERT INTO country VALUES ('AND', 'Andorra');
INSERT INTO country VALUES ('AGO', 'Angola');
INSERT INTO country VALUES ('AIA', 'Anguilla');
INSERT INTO country VALUES ('ATA', 'Antarctica');
INSERT INTO country VALUES ('ATG', 'Antigua and Barbuda');
INSERT INTO country VALUES ('ARG', 'Argentina');
INSERT INTO country VALUES ('ARM', 'Armenia');
INSERT INTO country VALUES ('ABW', 'Aruba');
INSERT INTO country VALUES ('AUS', 'Australia');
INSERT INTO country VALUES ('AUT', 'Austria');
INSERT INTO country VALUES ('AZE', 'Azerbaijan');
INSERT INTO country VALUES ('BHS', 'Bahamas');
INSERT INTO country VALUES ('BHR', 'Bahrain');
INSERT INTO country VALUES ('BGD', 'Bangladesh');
INSERT INTO country VALUES ('BRB', 'Barbados');
INSERT INTO country VALUES ('BLR', 'Belarus');
INSERT INTO country VALUES ('BEL', 'Belgium');
INSERT INTO country VALUES ('BLZ', 'Belize');
INSERT INTO country VALUES ('BEN', 'Benin');
INSERT INTO country VALUES ('BMU', 'Bermuda');
INSERT INTO country VALUES ('BTN', 'Bhutan');
INSERT INTO country VALUES ('BOL', 'Bolivia, Plurinational State of');
INSERT INTO country VALUES ('BES', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO country VALUES ('BIH', 'Bosnia and Herzegovina');
INSERT INTO country VALUES ('BWA', 'Botswana');
INSERT INTO country VALUES ('BVT', 'Bouvet Island');
INSERT INTO country VALUES ('BRA', 'Brazil');
INSERT INTO country VALUES ('IOT', 'British Indian Ocean Territory');
INSERT INTO country VALUES ('BRN', 'Brunei Darussalam');
INSERT INTO country VALUES ('BGR', 'Bulgaria');
INSERT INTO country VALUES ('BFA', 'Burkina Faso');
INSERT INTO country VALUES ('BDI', 'Burundi');
INSERT INTO country VALUES ('CPV', 'Cabo Verde');
INSERT INTO country VALUES ('KHM', 'Cambodia');
INSERT INTO country VALUES ('CMR', 'Cameroon');
INSERT INTO country VALUES ('CAN', 'Canada');
INSERT INTO country VALUES ('CYM', 'Cayman Islands');
INSERT INTO country VALUES ('CAF', 'Central African Republic');
INSERT INTO country VALUES ('TCD', 'Chad');
INSERT INTO country VALUES ('ZZZ', 'Channel Islands');
INSERT INTO country VALUES ('CHL', 'Chile');
INSERT INTO country VALUES ('CHN', 'China');
INSERT INTO country VALUES ('CXR', 'Christmas Island');
INSERT INTO country VALUES ('CCK', 'Cocos (Keeling) Islands');
INSERT INTO country VALUES ('COL', 'Colombia');
INSERT INTO country VALUES ('COM', 'Comoros');
INSERT INTO country VALUES ('COG', 'Congo');
INSERT INTO country VALUES ('COD', 'Congo, the Democratic Republic of the');
INSERT INTO country VALUES ('COK', 'Cook Islands');
INSERT INTO country VALUES ('CRI', 'Costa Rica');
INSERT INTO country VALUES ('CIV', 'Cote d''Ivoire');
INSERT INTO country VALUES ('HRV', 'Croatia');
INSERT INTO country VALUES ('CUB', 'Cuba');
INSERT INTO country VALUES ('CUW', 'Curacao');
INSERT INTO country VALUES ('CYP', 'Cyprus');
INSERT INTO country VALUES ('CZE', 'Czech Republic');
INSERT INTO country VALUES ('DNK', 'Denmark');
INSERT INTO country VALUES ('DJI', 'Djibouti');
INSERT INTO country VALUES ('DMA', 'Dominica');
INSERT INTO country VALUES ('DOM', 'Dominican Republic');
INSERT INTO country VALUES ('ECU', 'Ecuador');
INSERT INTO country VALUES ('EGY', 'Egypt');
INSERT INTO country VALUES ('SLV', 'El Salvador');
INSERT INTO country VALUES ('GNQ', 'Equatorial Guinea');
INSERT INTO country VALUES ('ERI', 'Eritrea');
INSERT INTO country VALUES ('EST', 'Estonia');
INSERT INTO country VALUES ('ETH', 'Ethiopia');
INSERT INTO country VALUES ('FLK', 'Falkland Islands (Malvinas)');
INSERT INTO country VALUES ('FRO', 'Faroe Islands');
INSERT INTO country VALUES ('FJI', 'Fiji');
INSERT INTO country VALUES ('FIN', 'Finland');
INSERT INTO country VALUES ('FRA', 'France');
INSERT INTO country VALUES ('GUF', 'French Guiana');
INSERT INTO country VALUES ('PYF', 'French Polynesia');
INSERT INTO country VALUES ('ATF', 'French Southern Territories');
INSERT INTO country VALUES ('GAB', 'Gabon');
INSERT INTO country VALUES ('GMB', 'Gambia');
INSERT INTO country VALUES ('GEO', 'Georgia');
INSERT INTO country VALUES ('DEU', 'Germany');
INSERT INTO country VALUES ('GHA', 'Ghana');
INSERT INTO country VALUES ('GIB', 'Gibraltar');
INSERT INTO country VALUES ('GRC', 'Greece');
INSERT INTO country VALUES ('GRL', 'Greenland');
INSERT INTO country VALUES ('GRD', 'Grenada');
INSERT INTO country VALUES ('GLP', 'Guadeloupe');
INSERT INTO country VALUES ('GUM', 'Guam');
INSERT INTO country VALUES ('GTM', 'Guatemala');
INSERT INTO country VALUES ('GGY', 'Guernsey');
INSERT INTO country VALUES ('GIN', 'Guinea');
INSERT INTO country VALUES ('GNB', 'Guinea-Bissau');
INSERT INTO country VALUES ('GUY', 'Guyana');
INSERT INTO country VALUES ('HTI', 'Haiti');
INSERT INTO country VALUES ('HMD', 'Heard Island and McDonald Islands');
INSERT INTO country VALUES ('VAT', 'Holy See (Vatican City State)');
INSERT INTO country VALUES ('HND', 'Honduras');
INSERT INTO country VALUES ('HKG', 'Hong Kong');
INSERT INTO country VALUES ('HUN', 'Hungary');
INSERT INTO country VALUES ('ISL', 'Iceland');
INSERT INTO country VALUES ('IND', 'India');
INSERT INTO country VALUES ('IDN', 'Indonesia');
INSERT INTO country VALUES ('IRN', 'Iran, Islamic Republic of');
INSERT INTO country VALUES ('IRQ', 'Iraq');
INSERT INTO country VALUES ('IRL', 'Ireland');
INSERT INTO country VALUES ('IMN', 'Isle of Man');
INSERT INTO country VALUES ('ISR', 'Israel');
INSERT INTO country VALUES ('ITA', 'Italy');
INSERT INTO country VALUES ('JAM', 'Jamaica');
INSERT INTO country VALUES ('JPN', 'Japan');
INSERT INTO country VALUES ('JEY', 'Jersey');
INSERT INTO country VALUES ('JOR', 'Jordan');
INSERT INTO country VALUES ('KAZ', 'Kazakhstan');
INSERT INTO country VALUES ('KEN', 'Kenya');
INSERT INTO country VALUES ('KIR', 'Kiribati');
INSERT INTO country VALUES ('PRK', 'Korea, Democratic People''s Republic of');
INSERT INTO country VALUES ('KOR', 'Korea, Republic of');
INSERT INTO country VALUES ('KWT', 'Kuwait');
INSERT INTO country VALUES ('KGZ', 'Kyrgyzstan');
INSERT INTO country VALUES ('LAO', 'Lao People''s Democratic Republic');
INSERT INTO country VALUES ('LVA', 'Latvia');
INSERT INTO country VALUES ('LBN', 'Lebanon');
INSERT INTO country VALUES ('LSO', 'Lesotho');
INSERT INTO country VALUES ('LBR', 'Liberia');
INSERT INTO country VALUES ('LBY', 'Libya');
INSERT INTO country VALUES ('LIE', 'Liechtenstein');
INSERT INTO country VALUES ('LTU', 'Lithuania');
INSERT INTO country VALUES ('LUX', 'Luxembourg');
INSERT INTO country VALUES ('MAC', 'Macao');
INSERT INTO country VALUES ('MKD', 'Macedonia, the former Yugoslav Republic of');
INSERT INTO country VALUES ('MDG', 'Madagascar');
INSERT INTO country VALUES ('MWI', 'Malawi');
INSERT INTO country VALUES ('MYS', 'Malaysia');
INSERT INTO country VALUES ('MDV', 'Maldives');
INSERT INTO country VALUES ('MLI', 'Mali');
INSERT INTO country VALUES ('MLT', 'Malta');
INSERT INTO country VALUES ('MHL', 'Marshall Islands');
INSERT INTO country VALUES ('MTQ', 'Martinique');
INSERT INTO country VALUES ('MRT', 'Mauritania');
INSERT INTO country VALUES ('MUS', 'Mauritius');
INSERT INTO country VALUES ('MYT', 'Mayotte');
INSERT INTO country VALUES ('MEX', 'Mexico');
INSERT INTO country VALUES ('FSM', 'Micronesia, Federated States of');
INSERT INTO country VALUES ('MDA', 'Moldova, Republic of');
INSERT INTO country VALUES ('MCO', 'Monaco');
INSERT INTO country VALUES ('MNG', 'Mongolia');
INSERT INTO country VALUES ('MNE', 'Montenegro');
INSERT INTO country VALUES ('MSR', 'Montserrat');
INSERT INTO country VALUES ('MAR', 'Morocco');
INSERT INTO country VALUES ('MOZ', 'Mozambique');
INSERT INTO country VALUES ('MMR', 'Myanmar');
INSERT INTO country VALUES ('NAM', 'Namibia');
INSERT INTO country VALUES ('NRU', 'Nauru');
INSERT INTO country VALUES ('NPL', 'Nepal');
INSERT INTO country VALUES ('NLD', 'Netherlands');
INSERT INTO country VALUES ('NCL', 'New Caledonia');
INSERT INTO country VALUES ('NZL', 'New Zealand');
INSERT INTO country VALUES ('NIC', 'Nicaragua');
INSERT INTO country VALUES ('NER', 'Niger');
INSERT INTO country VALUES ('NGA', 'Nigeria');
INSERT INTO country VALUES ('NIU', 'Niue');
INSERT INTO country VALUES ('NFK', 'Norfolk Island');
INSERT INTO country VALUES ('MNP', 'Northern Mariana Islands');
INSERT INTO country VALUES ('NOR', 'Norway');
INSERT INTO country VALUES ('OMN', 'Oman');
INSERT INTO country VALUES ('PAK', 'Pakistan');
INSERT INTO country VALUES ('PLW', 'Palau');
INSERT INTO country VALUES ('PSE', 'Palestine, State of');
INSERT INTO country VALUES ('PAN', 'Panama');
INSERT INTO country VALUES ('PNG', 'Papua New Guinea');
INSERT INTO country VALUES ('PRY', 'Paraguay');
INSERT INTO country VALUES ('PER', 'Peru');
INSERT INTO country VALUES ('PHL', 'Philippines');
INSERT INTO country VALUES ('PCN', 'Pitcairn');
INSERT INTO country VALUES ('POL', 'Poland');
INSERT INTO country VALUES ('PRT', 'Portugal');
INSERT INTO country VALUES ('PRI', 'Puerto Rico');
INSERT INTO country VALUES ('QAT', 'Qatar');
INSERT INTO country VALUES ('REU', 'Reunion');
INSERT INTO country VALUES ('ROU', 'Romania');
INSERT INTO country VALUES ('RUS', 'Russian Federation');
INSERT INTO country VALUES ('RWA', 'Rwanda');
INSERT INTO country VALUES ('BLM', 'Saint Barthelemy');
INSERT INTO country VALUES ('SHN', 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO country VALUES ('KNA', 'Saint Kitts and Nevis');
INSERT INTO country VALUES ('LCA', 'Saint Lucia');
INSERT INTO country VALUES ('MAF', 'Saint Martin (French part)');
INSERT INTO country VALUES ('SPM', 'Saint Pierre and Miquelon');
INSERT INTO country VALUES ('VCT', 'Saint Vincent and the Grenadines');
INSERT INTO country VALUES ('WSM', 'Samoa');
INSERT INTO country VALUES ('SMR', 'San Marino');
INSERT INTO country VALUES ('STP', 'Sao Tome and Principe');
INSERT INTO country VALUES ('SAU', 'Saudi Arabia');
INSERT INTO country VALUES ('SEN', 'Senegal');
INSERT INTO country VALUES ('SRB', 'Serbia');
INSERT INTO country VALUES ('SYC', 'Seychelles');
INSERT INTO country VALUES ('SLE', 'Sierra Leone');
INSERT INTO country VALUES ('SGP', 'Singapore');
INSERT INTO country VALUES ('SXM', 'Sint Maarten (Dutch part)');
INSERT INTO country VALUES ('SVK', 'Slovakia');
INSERT INTO country VALUES ('SVN', 'Slovenia');
INSERT INTO country VALUES ('SLB', 'Solomon Islands');
INSERT INTO country VALUES ('SOM', 'Somalia');
INSERT INTO country VALUES ('ZAF', 'South Africa');
INSERT INTO country VALUES ('SGS', 'South Georgia and the South Sandwich Islands');
INSERT INTO country VALUES ('SSD', 'South Sudan');
INSERT INTO country VALUES ('ESP', 'Spain');
INSERT INTO country VALUES ('LKA', 'Sri Lanka');
INSERT INTO country VALUES ('SDN', 'Sudan');
INSERT INTO country VALUES ('SUR', 'Suriname');
INSERT INTO country VALUES ('SJM', 'Svalbard and Jan Mayen');
INSERT INTO country VALUES ('SWZ', 'Swaziland');
INSERT INTO country VALUES ('SWE', 'Sweden');
INSERT INTO country VALUES ('CHE', 'Switzerland');
INSERT INTO country VALUES ('SYR', 'Syrian Arab Republic');
INSERT INTO country VALUES ('TWN', 'Taiwan, Province of China');
INSERT INTO country VALUES ('TJK', 'Tajikistan');
INSERT INTO country VALUES ('TZA', 'Tanzania, United Republic of');
INSERT INTO country VALUES ('THA', 'Thailand');
INSERT INTO country VALUES ('TLS', 'Timor-Leste');
INSERT INTO country VALUES ('TGO', 'Togo');
INSERT INTO country VALUES ('TKL', 'Tokelau');
INSERT INTO country VALUES ('TON', 'Tonga');
INSERT INTO country VALUES ('TTO', 'Trinidad and Tobago');
INSERT INTO country VALUES ('TUN', 'Tunisia');
INSERT INTO country VALUES ('TUR', 'Turkey');
INSERT INTO country VALUES ('TKM', 'Turkmenistan');
INSERT INTO country VALUES ('TCA', 'Turks and Caicos Islands');
INSERT INTO country VALUES ('TUV', 'Tuvalu');
INSERT INTO country VALUES ('UGA', 'Uganda');
INSERT INTO country VALUES ('UKR', 'Ukraine');
INSERT INTO country VALUES ('ARE', 'United Arab Emirates');
INSERT INTO country VALUES ('GBR', 'United Kingdom');
INSERT INTO country VALUES ('UMI', 'United States Minor Outlying Islands');
INSERT INTO country VALUES ('USA', 'United States of America');
INSERT INTO country VALUES ('URY', 'Uruguay');
INSERT INTO country VALUES ('UZB', 'Uzbekistan');
INSERT INTO country VALUES ('VUT', 'Vanuatu');
INSERT INTO country VALUES ('VEN', 'Venezuela, Bolivarian Republic of');
INSERT INTO country VALUES ('VNM', 'Viet Nam');
INSERT INTO country VALUES ('VGB', 'Virgin Islands, British');
INSERT INTO country VALUES ('VIR', 'Virgin Islands, U.S.');
INSERT INTO country VALUES ('WLF', 'Wallis and Futuna');
INSERT INTO country VALUES ('ESH', 'Western Sahara');
INSERT INTO country VALUES ('YEM', 'Yemen');
INSERT INTO country VALUES ('ZMB', 'Zambia');
INSERT INTO country VALUES ('ZWE', 'Zimbabwe');
INSERT INTO country VALUES ('XK', 'Kosovo');

INSERT INTO vaccine VALUES ('none', 'No vaccination');
INSERT INTO vaccine VALUES ('HepB_BD', 'Hepatitis B birth dose');
INSERT INTO vaccine VALUES ('HepB', 'Hepatitis B');
INSERT INTO vaccine VALUES ('Hib3', 'Hib3');
INSERT INTO vaccine VALUES ('HPV', 'HPV');
INSERT INTO vaccine VALUES ('JE', 'JE');
INSERT INTO vaccine VALUES ('MCV1', 'Measles 1');
INSERT INTO vaccine VALUES ('MCV2', 'Measles 2');
INSERT INTO vaccine VALUES ('Measles', 'Measles (used in campaigns only)');
INSERT INTO vaccine VALUES ('MenA', 'MenA');
INSERT INTO vaccine VALUES ('PCV3', 'PCV3');
INSERT INTO vaccine VALUES ('Rota', 'Rota');
INSERT INTO vaccine VALUES ('Rubella', 'Rubella');
INSERT INTO vaccine VALUES ('YF', 'Yellow fever vaccine');
INSERT INTO vaccine VALUES ('MR_Measles', 'Measles (sdf6/7 only)');

INSERT INTO gavi_support_level VALUES ('none', 'No vaccination');
INSERT INTO gavi_support_level VALUES ('without', 'Vaccination without GAVI support');
INSERT INTO gavi_support_level VALUES ('with', 'Vaccination with GAVI support');
INSERT INTO gavi_support_level VALUES ('hold2010', 'Vaccination levels held at 2010 levels (SDF8 only)');
INSERT INTO gavi_support_level VALUES ('bestminus', 'Best minus no vaccination (sdf6/7 only)');

INSERT INTO demographic_value_unit VALUES (1, 'Births per person in population');
INSERT INTO demographic_value_unit VALUES (2, 'Births per woman in age band');
INSERT INTO demographic_value_unit VALUES (3, 'Births per woman');
INSERT INTO demographic_value_unit VALUES (4, 'Deaths per live birth');
INSERT INTO demographic_value_unit VALUES (5, 'Deaths per person in population');
INSERT INTO demographic_value_unit VALUES (6, 'Male births per female birth');
INSERT INTO demographic_value_unit VALUES (7, 'Net rate of migration');
INSERT INTO demographic_value_unit VALUES (8, 'Number of births');
INSERT INTO demographic_value_unit VALUES (9, 'Number of deaths');
INSERT INTO demographic_value_unit VALUES (10, 'Number of people');
INSERT INTO demographic_value_unit VALUES (11, 'Number of survivors');
INSERT INTO demographic_value_unit VALUES (12, 'Probability');
INSERT INTO demographic_value_unit VALUES (13, 'Years');

INSERT INTO disease VALUES ('HepB', 'HepB');
INSERT INTO disease VALUES ('Hib', 'Hib');
INSERT INTO disease VALUES ('HPV', 'HPV');
INSERT INTO disease VALUES ('JE', 'JE');
INSERT INTO disease VALUES ('Measles', 'Measles');
INSERT INTO disease VALUES ('MenA', 'MenA');
INSERT INTO disease VALUES ('PCV', 'PCV');
INSERT INTO disease VALUES ('Rota', 'Rotavirus');
INSERT INTO disease VALUES ('Rubella', 'Rubella');
INSERT INTO disease VALUES ('YF', 'Yellow fever');

INSERT INTO responsibility_set_status VALUES ('incomplete', 'There are responsibilities left to upload');
INSERT INTO responsibility_set_status VALUES ('submitted', 'All resonsibilities have been submitted');
INSERT INTO responsibility_set_status VALUES ('approved', 'All resonsibilities have been approved');

INSERT INTO impact_outcome VALUES ('deaths_averted', 'deaths averted');
INSERT INTO impact_outcome VALUES ('cases_averted', 'cases averted');
INSERT INTO impact_outcome VALUES ('fvps_added', 'fvps_added');
INSERT INTO impact_outcome VALUES ('da_rate', 'da_rate (LEGACY ONLY - perhaps)');

INSERT INTO support_type VALUES ('total', 'Difference between no vaccination and best estimate (in gavi_support_level)');
INSERT INTO support_type VALUES ('gavi', 'Difference between no gavi and best estimate (in gavi_support_level)');
