#!/usr/bin/env bash
set -e

ROOT=$(dirname $(dirname $(realpath $0)))

DB_SHA=$(git -C $ROOT rev-parse --short=7 HEAD)
DB_BRANCH=$(git -C $ROOT symbolic-ref --short HEAD)

DB_DOCS_PATH=$ROOT/docs/www
DB_DOCS_REPO=`cat $ROOT/docs/destination_repo`

if [ $DB_BRANCH != "master" ]; then
    echo "Not generating docs for branch $DB_BRANCH"
    exit 0
fi


if [ -d $DB_DOCS_PATH ]; then
    echo "Updating sources"
    git -C $DB_DOCS_PATH fetch
    git -C $DB_DOCS_PATH checkout master
    git -C $DB_DOCS_PATH reset --hard origin/master
else
    git clone "$DB_DOCS_REPO" $DB_DOCS_PATH
fi

echo "Installing dependencies"
pip3 install --user -r $ROOT/docs/requirements.txt

echo "Generating documentation"
$ROOT/docs/generate.py $DB_SHA $DB_DOCS_PATH

echo "Pushing to github"
git -C $DB_DOCS_PATH push
